apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: <collection-name>-build-only-manual-pipeline-run
spec:
  serviceAccount: kabanero-operator
  timeout: "1h0m0s"
  pipelineRef:
    name: <collection-name>-build-only-pipeline
  trigger:
    type: manual
  resources:
    - name: git-source
      resourceRef:
        name: git-source