#Kabanero! on activate substitute StackId for text 'StackId'
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: StackId-validate-stack-task
spec:
  inputs:
    resources:
    - name: git-source
      type: git
  steps:
  - name: validate-stack-is-active
    securityContext:
      privileged: true
    image: kabanero/validate-collection:0.1
    command: ["/bin/bash"]
    args:
    - -c
    - "/validate.sh"
    env:
    - name: gitsource
      value: git-source
