#Kabanero! on activate substitute CollectionId for text 'CollectionId'
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: CollectionId-validate-collection-task
spec:
  inputs:
    resources:
    - name: git-source
      type: git
  steps:
  - name: validate-collection-is-active
    securityContext:
      privileged: true
    image: kabanero/validate-collection:0.1
    command: ["/bin/bash"]
    args:
    - -c
    - "/validate.sh"
    env:
    - name: gitsource
      value: git-source